## https://projecteuler.net/problem=2
## Even Fibonacci Numbers
## Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
## By starting with 1 and 2, the first 10 terms will be:
## 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots
## By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
## find the sum of the even-valued terms.

cap <- 4e6

## Brute force--------------------
total <- 1
even_total <- 0
x0 <- 1
x1 <- 1

while (x1 < cap) {
    x2 <- x1 + x0
    
    total <- total + x2
    if (x2 %% 2 == 0) {
        even_total <- even_total + x2
    }
    
    x0 <- x1
    x1 <- x2
}

print(even_total)

## Phi method ----------------
## The nth fibonacci number is round(phi^n/sqrt(5)) - this uses the definition where it starts 1, 1 however
sqrt_5 <- sqrt(5) ## I am speed - this number gets used a lot
phi <- (1 + sqrt_5)/2

# 4e6 > phi^n / sqrt_5 => log(4e6*sqrt_5) / log(phi) > n
ncap <- floor(log(cap*sqrt_5) / log(phi))

## Even ones are every third, starting at the third (using the 1, 1 definition)
even_locs <- seq(3, ncap, by = 3)

sum(round(phi^even_locs / sqrt_5))
