## https://projecteuler.net/problem=12
## Highly Divisible Triangular Number
## The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
## 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, \dots
## Let us list the factors of the first seven triangle numbers:
## \begin{align}
## \mathbf 1 &amp;\colon 1\\
## \mathbf 3 &amp;\colon 1,3\\
## \mathbf 6 &amp;\colon 1,2,3,6\\
## \mathbf{10} &amp;\colon 1,2,5,10\\
## \mathbf{15} &amp;\colon 1,3,5,15\\
## \mathbf{21} &amp;\colon 1,3,7,21\\
## \mathbf{28} &amp;\colon 1,2,4,7,14,28
## \end{align}
## We can see that 28 is the first triangle number to have over five divisors.
## What is the value of the first triangle number to have over five hundred divisors?

## Triangle numbers = n(n + 1) / 2 = (n^2 + n)/2
## For even values of n, the number must therefore be able to be expressed as the products of n/2 and of n + 1
## For odd values of n, the number must therefore be able to be expressed as the products of n and of (n + 1) / 2

## A number with divisors must be expressible in the form x1^n1 * x2^n2 * x3^n3... where xi is prime and ni is an integer
## Such a number will have (n1+1)*(n2+1)*(n3+1)... divisors
## Using arithmetic mean >= geometric mean,
## ((n1 + 1) + (n2 + 1)... + (nk + 1)) / k >= ((n1+1)*(n2+1)*(n3+1)...(nk + 1))^(1/k)
## (sum(n) / k + 1)^k >= (n1+1)*(n2+1)*(n3+1)...(nk + 1)
## Thus we can determine an upper limit of divisors based on the number of prime factors

n <- 4
even <- n %% 2 == 0
found <- F

while (!found && n < 62366) {
    triangle <- n * (n + 1) / 2
    
    if (even) {
        divisors <- c(get_prime_divisors(n / 2), get_prime_divisors(n + 1))
    } else {
        divisors <- c(get_prime_divisors(n), get_prime_divisors((n + 1) / 2))
    }
    
    k <- uniqueN(divisors)
    
    upper_bound <- (length(divisors) / k + 1) ^ k
    
    if (upper_bound > 500) {
        prime_table <- table(divisors)
        
        if (prod(prime_table + 1) > 500) {
            found <- T
        }
    }
    
    n <- n + 1
    even <- !even
}

n <- n - 1
even <- !even

print(triangle)
